### ISSUE TITLE
Aubio doesn't check if fftw support is enabled in libsamplerate

### ISSUE THREAD

**Issue by RomainNaour** [aubio/aubio#100]
Hi,

From the discussion on the Buildroot mailing list [1].

Is libsamplerate build without fftw support (--disable-fftw) is really usable with aubio build with fftw single precision mode ?

The aubio build system doesn't check whether fftw support is present in libsamplerate, it's an issue ?

Best regards,
Romain

[1] http://lists.busybox.net/pipermail/buildroot/2017-April/189699.html

**Comment by piem** [comment]
hi @RomainNaour,

What could be the issue exactly? fftw is optional in both aubio and libsamplerate. I don't see why aubio should be check on how libsamplerate was built.

Also, note that libsamplerate.so is not linked against fftw3, which is only used in libsamplerate tests.

Otherwise, congrats for opening issue #100! :tada: :smiley: 

best, piem

**Comment by RomainNaour** [comment]
Hi @piem 

> Also, note that libsamplerate.so is not linked against fftw3, which is only used in libsamplerate tests.

Haa indeed, I missed that --disable-fftw is only for the libsamplerate tests. Tests are disabled in the Buildroot packaging. So no issue at all :)

I didn't noticed that was the #100, so a easy one :p 

Best regards,
Romain
