### ISSUE TITLE
Some NULL pointer dereference(DoS) Vulnerabilities were found in aubio

### ISSUE THREAD

**Issue by IvanCql** [aubio/aubio#137]
Hi, I found some NULL pointer dereference(DoS) Vulnerabilities in aubio:
<a href="https://github.com/IvanCql/vulnerability/blob/master/An%20NULL%20pointer%20dereference(DoS)%20Vulnerability%20was%20found%20in%20function%20%20aubio_source_avcodec_readframe%20of%20aubio.md">An NULL pointer dereference(DoS) Vulnerability was found in function aubio_source_avcodec_readframe of aubio</a>
<a href="https://github.com/IvanCql/vulnerability/blob/master/An%20NULL%20pointer%20dereference(DoS)%20Vulnerability%20was%20found%20in%20function%20swri_audio_convert%20of%20ffmpeg%20libswresample.md">An NULL pointer dereference(DoS) Vulnerability was found in function swri_audio_convert of ffmpeg libswresample</a>

**Comment by piem** [comment]
hello @IvanCql 

thanks for reporting this. it is not trivial to fix, but i'm looking into it. See also #148.

best, piem

**Comment by IvanCql** [comment]
CVE-2017-17554、CVE-2017-17555

**Comment by piem** [comment]
The patch a81b12a in [`fix/avr_context`](https://github.com/aubio/aubio/compare/fix/avr_context) fixes CVE-2017-17554. Note that `libsndfile`, if compiled in, will still process the corrupt file.

The second crash, CVE-2017-17555, was due to aubio trying to run `swresample` on a different number of channels than configured for, as rightly noted by Carl Eugen in [Debian bug #884232](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=884232). This is fixed in 265fe9a2.

best, piem
