### ISSUE TITLE
Not sending MIDI note-off via JACK

### ISSUE THREAD

**Issue by mj15003** [aubio/aubio#183]
Hi Paul,
because I am not so good at investigating someone else's code I am trying to submit, let's say bug report.

Steps what I am doing to reproduce it.

1. Start JACK
2. Start aubionotes in jack mode
3. Start jack_midi_dump -r
4. Connect aubionotes MIDI out to jack_midi_dump MIDI In
5. Playing test signal from Audacity to aubionotes jack audio In
    Test signal is 0.5s 50 Hz Sine - 0.1s silence - 0.5s 100 Hz Sine - 0.1s silence - 0.5s 150 Hz Sine - 0.1s silence - 0.5s 200 Hz Sine - 0.1s silence - 0.5s 250 Hz Sine - 0.1s silence- 0.5s 300 Hz Sine - 0.1s silence - 0.5s 350 Hz Sine - 0.1s silence - 0.5s 400 Hz Sine.

This is what I get from jack_midi_dump : 

+745344: 80 23 00 note off (channel  0): pitch  35, velocity   0
  +26368: 90 33 7a note on  (channel  0): pitch  51, velocity 122
          +0: 90 33 7a note on  (channel  0): pitch  51, velocity 122
  +26624: 90 38 7a note on  (channel  0): pitch  56, velocity 122
          +0: 90 38 7a note on  (channel  0): pitch  56, velocity 122
  +26368: 90 3b 79 note on  (channel  0): pitch  59, velocity 121
          +0: 90 3b 79 note on  (channel  0): pitch  59, velocity 121
  +26624: 90 3e 7a note on  (channel  0): pitch  62, velocity 122
          +0: 90 3e 7a note on  (channel  0): pitch  62, velocity 122
  +26368: 90 41 7a note on  (channel  0): pitch  65, velocity 122
          +0: 90 41 7a note on  (channel  0): pitch  65, velocity 122
  +26624: 90 43 7a note on  (channel  0): pitch  67, velocity 122
          +0: 90 43 7a note on  (channel  0): pitch  67, velocity 122

Sample rate is 44100 Hz. Amplitude is constant 0.8. Timestamps are relative (I presume in samples). Only one note off at the beginning when the 50 Hz sine is playing. And with each frequency change two midi note ons at the same time. I don't understand whats going on. Anything what is more or less correct is the pitch. 

Again thanks for your help in advance.

Miroslav

**Comment by flappix** [comment]
This seems to be a bug since version 0.4.5. In version 0.4.4 it works fine.
I also noticed that notes deeper than A# (116.5 Hz) does not get a note on event but a note off event instead.

The chosen pitch detection and on-set algorithm seems to have no effect on this, the behavior is nearly the same for all options. Also changing the buffer and hop size does not change anything related to this bug.

**Comment by piem** [comment]
hi @flappix and @mj15003 

@flappix you are correct, this was instroduced in 8f0db97 (0.4.5) and should be fixed in master now thanks to @cyclopsian with f7771c6. Can you have a try and see if you still see missing note events in master?

About the other parameters:
 - the pitch detection algorithm should definitely make a difference, but maybe not one that is easy to hear, since the frequencies are quantized to the nearest midi note.
 - for a samplerate of 44.1kHz, the defaults buffer and hop sizes should be ok.
 - If you feel like experimenting, you may want to try longer window (e.g. buffer) sizes to increase the precision in the low frequencies
 - you can also try to decrease hop_size to increase the temporal resolution of the pitch estimates.

**Comment by mj15003** [comment]
I have tested it recently. The note-offs seem to be sent correctly, however always in exact time with the beginning of the next note on, even if the input sound contains silence. If I analyze the same sound as input file I get the same information in pitch-begintime-endtime format in terminal. It seems to me that like aubionotes ignores silence (digital silence, certainly lower than default -90dB) at all.

**Comment by cyclopsian** [comment]
@mj15003 As far as I can tell that behavior is consistent with 0.4.4. Would be nice to have it fixed though. Maybe a separate bug?

**Comment by piem** [comment]
hi @mj15003 and @cyclopsian 

I confirm the bug is different issue. I've just opened #203 to address the late note-off issue.

cheers, piem
