### ISSUE TITLE
Another SEGV signal problem found

### ISSUE THREAD

**Issue by fCorleone** [aubio/aubio#188]
When I run the program aubionotes. The address sanitizer showed this:
```
=================================================================
==7800==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000004 (pc 0x7f0348775d3a bp 0x000000000007 sp 0x7fffc0b26750 T0)
    #0 0x7f0348775d39 in aubio_pitch_set_unit ../src/pitch/pitch.c:324
    #1 0x7f034876d079 in new_aubio_notes ../src/notes/notes.c:87
    #2 0x4051d4 in main ../examples/aubionotes.c:69
    #3 0x7f034838082f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #4 0x401508 in _start (/home/mfc_fuzz/aubio/build/dist/usr/local/bin/aubionotes+0x401508)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../src/pitch/pitch.c:324 aubio_pitch_set_unit
==7800==ABORTING

```
The input file of the program has been displayed at: https://github.com/fCorleone/fuzz_programs/blob/master/aubio/testcase3
The command line is just ./aubionotes testcase3

**Comment by piem** [comment]
Hi again,

Two problems here, when processing a corrupt file with negative samplerates:

 - `aubio_notes` algorithm would keep trying even after pitch creation failed,
 - `aubio_source_wavread` would not give up when samplerate < 0 

These two should be fixed in the branch [`fix/negative_samplerate`](https://github.com/aubio/aubio/compare/fix/negative_samplerate).

thanks for reporting, piem
