### ISSUE TITLE
Question : performances of memory copy

### ISSUE THREAD

**Issue by OlivierSohn** [aubio/aubio#194]
Hello,

I wonder if the order used below is based on a performance comparison (aubio_ippsCopy is `faster` than `aubio_ippsCopy` which is faster than ...) or if it's just any order.

Thanks!

```c++
void fvec_copy(const fvec_t *s, fvec_t *t) {
  if (s->length != t->length) {
    AUBIO_ERR("trying to copy %d elements to %d elements \n",
        s->length, t->length);
    return;
  }
#if defined(HAVE_INTEL_IPP)
  aubio_ippsCopy(s->data, t->data, (int)s->length);
#elif defined(HAVE_ATLAS)
  aubio_cblas_copy(s->length, s->data, 1, t->data, 1);
#elif defined(HAVE_ACCELERATE)
  aubio_vDSP_mmov(s->data, t->data, 1, s->length, 1, 1);
#elif defined(HAVE_MEMCPY_HACKS)
  memcpy(t->data, s->data, t->length * sizeof(smpl_t));
#else
  uint_t j;
  for (j = 0; j < t->length; j++) {
    t->data[j] = s->data[j];
  }
#endif
}
```

**Comment by piem** [comment]
hi @OlivierSohn 

Order preference of the optimizations is not based on measurements, but rather trying to guess which configuration a user might prefer on different platforms.

So that routines most specific to a platform or vendor should go to the top, falling back to the next less specific routines.

for instance:
 - if configured with atlas on linux, it will be preferred over memcpy
 - if configured with ipp on osx, it will be preferred over vDSP.

It is possible to enable/disable each of these options, so you should be evaluate the performance of a couple of configurations for your environment.

Note: the code you pasted was modified, i've just updated it to match current master.

Let us know if that answers your questions!

best, piem

**Comment by OlivierSohn** [comment]
Yes, thanks very much!
