### ISSUE TITLE
cvec_t length is semantically inappropriate, and cuases trouble.

### ISSUE THREAD

**Issue by sorenchiron** [aubio/aubio#333]
The acutall length of `cvec_t` is cast to `length/2 + 1` only for FFT convienence.
This causes logical inconvenience and ambiguity for user-customized usage of `cvec_t` struct.
Which, further causes memory leakage/malaccess when this shortened length was used in code.

Logcially speaking, complex-vector behaviour and specific FFT feature should be decoupled. `cvec_t` should not be constructed only for FFT. This makes the exposed `cvec_t` struct being more like a leaked internal sturct.

The following snippet shows the original source of cvec struct.

```
cvec_t * new_cvec(uint_t length) {
  cvec_t * s;
  if ((sint_t)length <= 0) {
    return NULL;
  }
  s = AUBIO_NEW(cvec_t);
  s->length = length/2 + 1;
  s->norm = AUBIO_ARRAY(smpl_t,s->length);
  s->phas = AUBIO_ARRAY(smpl_t,s->length);
  return s;
}
```

**Comment by piem** [comment]
hi @sorenchiron 

sorry if that design is confusing to you. you could just consider it as an opaque struct, and use the functions provided in the library to access the elements of `cvec_c`. the design is certainly not going to change.

otherwise i'm not aware of any leak in the aubio library right now. if you find one, please open a new issue!

cheers, piem
