### ISSUE TITLE
Error when using resampler: aubio was not compiled with libsamplerate

### ISSUE THREAD

**Issue by dantarakan** [aubio/aubio#44]
Hi,

I am using aubio in my Swift, so I compiled a framework using the build_apple_frameworks script.
Inside the application I tried to resample an audio file like this:

```swift
// Initialise the resampler
let resampler = new_aubio_resampler(ratio, 0)
// Convert [Float] to fvec
let inRecArray = new_fvec(UInt32(floatArray.count))
for(var i=0; i<floatArray.count; i++)
{
    fvec_set_sample(inRecArray, floatArray[i], UInt32(i))
}
// Calculate length of the output
let len = UInt32(ceil(Double(floatArray.count)*Double(ratio)))
// Initialise output vector
var outRecArray = new_fvec(len)
// Perform resampling
aubio_resampler_do(resampler, inRecArray, outRecArray)
// Print the result
fvec_print(outRecArray)
```

However I'm getting the following error:

> aubio was not compiled with libsamplerate

Is there a way to pass options to the build_apple_frameworks script? 
I've tried tweaking Line 243 in wscript to the following:
`if (ctx.options.enable_samplerate == False):`

But I still get the same error.

**Comment by piem** [comment]
hi @dantarakan,

First, please note that the preferred way to resample a sound file is to open it using the desired samplerate. For instance, if you create an `aubio_source` with 8000Hz, the file will be automatically be resampled to 8000Hz, regardless its actual samplerate.

On apple platforms, the resampling is done automatically, so there is no need to use `aubio_resampler` at all.

Now, if you really need to resample a signal that is already loaded, you can pass `--enable-samplerate` to `waf` to force building aubio with libsamplerate. You will need to install libsamplerate first, for instance with `brew install libsamplerate`. This works on macosx. I never tried this on iOS though.

The `WAFCONF` variable in `build_apple_frameworks` explicitely contains `--disable-samplerate`. You could just remove it, so that libsamplerate will be automatically used when available.

Let me know how it goes,

best, Paul

**Comment by dantarakan** [comment]
Hi @piem ,

Thank you for the advice!
Having removed `--disable-samplerate`, and installed libsamplerate via homebrew, I got errors from the `build_apple_frameworks`, telling me that symbols for architecture i386 are undefined.

I then rebuilt libsamplerate from source, while specifying necessary architecture flags, using this command:

```sh
./configure CFLAGS='-arch i386 -arch x86_64 -arch arm64' LDFLAGS='-arch i386 -arch x86_64 -arch arm64' && make && make install
```

However, this build failed, because G++ couldn't find the iPhone SDK, necessary to support the arm64 architecture.

This could be fixed by specifying path to the SDK, or building the library using XCode, however I decided not to bother with this. Instead, I followed your suggestions, and created an `aubio_source` with 16kHz, and everything went well.

I believe that this "workaround" would be preferential to using the resampler, thus I would consider this issue resolved.

Paul, thank you very much for your time, this is a truly awesome library!

Best,
Daniil
