### ISSUE TITLE
Different tempo result for different sampling rates

### ISSUE THREAD

**Issue by lyssdod** [aubio/aubio#50]
Hi again @piem,

Can not determine if that's a bug or feature...I'm using the same script from #49, however, it gives various outputs for 44100 kHz wav file and 22050 one. If file is converted from stereo to mono, I have another (third) variant. Does it supposed to be so?

**Comment by lyssdod** [comment]
Script source

```python

import numpy
from aubio import source, tempo

def get_bpm(filename = 'output.wav'):
    win_s = 512                 # fft size
    hop_s = win_s / 2           # hop siz

    samplerate = 0
    s = source(filename, samplerate, hop_s)
    samplerate = s.samplerate
    o = tempo("default", win_s, hop_s, samplerate)

    print samplerate
    # list of beats, in samples
    beats = []
  
    # total number of frames read
    total_frames = 0
    while True:
        samples, read = s()
        is_beat = o(samples)
        if is_beat:
            this_beat = o.get_last_s()
            beats.append(this_beat)
        total_frames += read
        if read < hop_s: break

    s.close()
    
    if len(beats) > 1:
        bpms = 60./ numpy.diff(beats)
        print round(numpy.median(bpms), 3)

get_bpm('test.wav')
```

**Comment by lyssdod** [comment]
Here are results for three files (44.1 stereo, 22.05 stereo, 44.1 mono):

```
$ python2 test.py 
44100
116.231
$ python2 test.py 
22050
175.488
$ python2 test.py 
44100
117.023
```

**Comment by piem** [comment]
Hi @lyssdod ,

If the input signal changes (by resampling and / or downmixing it), the algorithm will give different results. But not necessarily worst. Down sampling will generally make the process much faster, at the price of a lower temporal resolution.

In your above script, win_s and hop_s should depend of the sample rate so that win_s would be about 23ms, and hop_s about half that. At the same time, the process will run much faster if these sizes are power of two.

See [demo_bpm_extract.py](https://github.com/aubio/aubio/blob/develop/python/demos/demo_bpm_extract.py) for some example of parameter values with the tempo algorithm.

**Comment by lyssdod** [comment]
Thanks! Will alter these params.

**Comment by lyssdod** [comment]
With win_s = 512 and hop_s = 256, script return right results for 22050 Hz samplerate. Can be closed now.
