### ISSUE TITLE
Ubuntu's version segment faults with Python pitch if window too large

### ISSUE THREAD

**Issue by fnielsen** [aubio/aubio#63]
My version of aubio segment faults Python if the submitted window is too large in the pitch function/object. The code below produces the error:

    import aubio
    import numpy as np

    samples = np.random.randint(255, size=(1025,))
    f_samples = samples.astype(np.float32)
    pitcher = aubio.pitch()
    pitch = pitcher(f_samples)

I was expecting at an exception or handling of the window.

My version is Ubuntu LTS 16.04 package aubio-tools and python-aubio Version: 0.4.1-2build4.

**Comment by piem** [comment]
Hi @fnielsen ,

Thanks for your report. I believe this was fixed in the latest commit.

To test the latest python module from the master git branch without conflicting with your existing installation, you should be able to install it in a virtualenv:

```
$ virtualenv aubio-master
$ source aubio-master/bin/activate
$ pip install git+
```

With the above example, i know get:

```
ValueError: input size of pitch should be 512, not 1025
```

Let us know how it works for you,

Best, Paul

**Comment by fnielsen** [comment]
Excellent. I can confirm the "ValueError" exception now with the present Github version of aubio. Thanks.

**Comment by piem** [comment]
Great, thanks for testing it out @fnielsen. There may be some more checks to add in `python/ext`, let us know if you run into any other bug.

Best, Paul
