### ISSUE TITLE
What/where is aubio.task?

### ISSUE THREAD

**Issue by notalentgeek** [aubio/aubio#72]
I am trying these codes, [https://chrisbaume.wordpress.com/2013/02/09/aubio-alsaaudio/](https://chrisbaume.wordpress.com/2013/02/09/aubio-alsaaudio/). However, it returns this error.

```markdown
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from aubio.task import *
ImportError: No module named task
```

I looked around Internet and cannot found the solution. Until I saw the comment from the author.

> Seems that’s is a bug, and you can get some workaround changing your release version number, but i didn’t tried yet and really don’t need it just now.

**Comment by piem** [comment]
hi @notalentgeek ,

aubio.task is long gone. The python module for aubio has been rewritten since.

I have just committed a similar example that uses the latest python aubio module:

[`python/demos/demo_alsa.py`](/aubio/aubio/tree/master/python/demos/demo_alsa.py)

Let me know how it works for you,

Best, Paul

**Comment by notalentgeek** [comment]
Hei @piem that is perfect as what I want! Thanks!
