### ISSUE TITLE
How to feed in a WAV file to get its pitch?

### ISSUE THREAD

**Issue by starkshaw** [aubio/aubio#88]
Hello, I am really new here... And the question seems silly, but I still don't know how exactly aubio works. I have already read some example code of `io`, `aubiopitch` and `fvec`, have only basic knowledge in this. So my question, as mentioned above, is how to feed the data from WAV to eventually let the pitch detection part recognize it and extract its pitch? Tried some ways but not sure how to bridge `aubio_source_t *input = new_aubio_source` to `fvec` then eventually to `aubio_pitch_t *o = new_aubio_pitch`.

If you could help me in C, I would be very appreciated. :)

**Comment by piem** [comment]
hello and welcome @starkshaw 

I'm sure you had a look in the `tests` folder already:

 - [`tests/src/pitch/test-pitch.c`](https://github.com/aubio/aubio/blob/master/tests/src/pitch/test-pitch.c)
 - [`tests/src/tempo/test-tempo.c`](https://github.com/aubio/aubio/blob/master/tests/src/tempo/test-tempo.c)

The [second example, `test-tempo.c`](https://github.com/aubio/aubio/blob/master/tests/src/tempo/test-tempo.c) is complete with file reading and feeding the blocks read to the `tempo` algorithm.

Starting from there, and looking at the [pitch example](https://github.com/aubio/aubio/blob/master/tests/src/pitch/test-pitch.c), you should soon be extracting pitch instead of beats.

Let us know how it goes!

best, paul

**Comment by starkshaw** [comment]
Hey @piem Thanks for your advice. I finally got it worked! 💯
