### ISSUE TITLE
Onsets from Tempo detection object

### ISSUE THREAD

**Issue by 7heW4yne** [aubio/aubio#96]
Hello,

I just played a bit with the onset and tempo detection. It is really a nifty piece of work! Thanks for that! :)

But I'm astonished that the tempo detection performs an onset detection internally, but does not provide the detected onsets. If I want the onsets AND beats for 1 file, I have to do the same work twice and perform an additional onset detection.

So is there a reason why the tempo detection does not provide onset positions as well as beats?

Best, Joerg

**Comment by piem** [comment]
hi @7heW4yne 

the reason is _do one thing, do it well_: this allows for different parameters to be used for beats and onsets, and to optimise them independently (novelty function, frame rate, threshold...).

if speed is a concern (aubio is quite fast already), see [`src/tempo/tempo.c#L83`](https://github.com/aubio/aubio/blob/master/src/tempo/tempo.c#L83): you can store the output of the peak picker in a second element of tempo's output, then check on `tempo->data[1] > 0.` to see if the current frame was detected as an onset.

side note: the branch `awhitening` was recently merged in master, and should improve onset performance quite a bit.  See dccfad2 for more info.

hth, piem

**Comment by 7heW4yne** [comment]
hi piem

thanks for your response.

I was wondering why you do everything in the tempo detection step by step, instead of using an onset detection object with another configuration.
However, I now see that the onset detection for the tempo object does also not have a "minio" parameter and returns slightly different results compared to an extra onset detection.

But you are right. aubio IS fast. Altough it might be even faster by using OpenMP and intrinsics in some places. (As an example: I think the [SoundTouch library](https://sourceforge.net/projects/soundtouch/) has some MMX/SSE optimized cross correlation functions.)
But this is only nice to have :)

Thanks, Joerg

**Comment by piem** [comment]
also, acceleration libraries which are not CPU specific, such as cblas or Accelerate, are preferred in aubio, so that a maximum of architectures can benefit these accelerations. Patches adding support for mmx/sse are welcome though ;-)
